# Can be either http://... or unix://...
listen_mode: http://127.0.0.1:4000

http_max_body_size: 10485760 # 10 MB

database_url: sqlite://appledb.sqlite

web_sources_path: web/dist

max_concurrent_tasks: 10

serve_openapi: true

cors_allowed_origins:
  - http://localhost:5173

watched_directory: /tmp/appledb
