//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "entitlement")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub key: String,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::executable_entitlement::Entity")]
    ExecutableEntitlement,
}

impl Related<super::executable_entitlement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutableEntitlement.def()
    }
}

impl Related<super::executable_operating_system_version::Entity> for Entity {
    fn to() -> RelationDef {
        super::executable_entitlement::Relation::ExecutableOperatingSystemVersion.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::executable_entitlement::Relation::Entitlement
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
