//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "executable")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub full_path: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::executable_operating_system_version::Entity")]
    ExecutableOperatingSystemVersion,
}

impl Related<super::executable_operating_system_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutableOperatingSystemVersion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
