//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod entitlement;
pub mod executable;
pub mod executable_entitlement;
pub mod operating_system;
pub mod operating_system_version;
