//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "operating_system_version")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: String,
    pub operating_system_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::executable::Entity")]
    Executable,
    #[sea_orm(
        belongs_to = "super::operating_system::Entity",
        from = "Column::OperatingSystemId",
        to = "super::operating_system::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OperatingSystem,
}

impl Related<super::executable::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Executable.def()
    }
}

impl Related<super::operating_system::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OperatingSystem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
